**: {
  style: {
    border-radius: 8
  }
}

thyphoonKingdom: Thyphoon Kingdom {
  frostFamily: Frost Family {
    Tiberius -> Alaric: father and son
    Alaric -> Kieron: father and son
  }

  thyphoonAcedemy: Thyphoon Acedemy {
    Alfwyn: Master Alfwyn
  }

  centralArmy: Central Army {
    Darius: Darius - Dark Knight
  }

  centralArmy -> frostFamily: army of
}

northWolfs: North Wolfs {
  starkFamily: Stark Family {
    Rowan -> Lyanna: brother and sister
  }

  targaryenFamily: Targaryen Family {
    Aegon
  }

  starkFamily <-> targaryenFamily: ally
}

lightChurch: Light Church {
  DominicKane: Kane - First Knight
  Luminara: Luminara - Archbishop
}

shadowChurch: Shadow Church {
  Valkyrie
}
